id: P008029
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09670
  title: འབྲི་གུང་གྲུབ་དབང་ཨ་མགོན་རིན་པོ་ཆེའི་རྣམ་ཐར།
  author: ''
  volumes:
    46101db25127476cbea5cc7db63298b4:
      image_group_id: I00KG09675
      title: ''
      volume_number: 1
      total_pages: 90
ebook_metadata:
  title: འབྲི་གུང་གྲུབ་དབང་ཨ་མགོན་རིན་པོ་ཆེའི་རྣམ་ཐར།
  author: ''
  sku: P008029
  cover: cover.jpg
  layers:
  - pagination
